// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NTR.Data;

#nullable disable

namespace NTR.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220116141545_Initial2")]
    partial class Initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NTR.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Frozen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.Property<string>("SubcodeName")
                        .HasColumnType("varchar(95)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ActivityId");

                    b.HasIndex("ProjectCode");

                    b.HasIndex("SubcodeName");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("NTR.Models.Project", b =>
                {
                    b.Property<string>("ProjectCode")
                        .HasColumnType("varchar(95)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectCode");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("NTR.Models.ProjectPartake", b =>
                {
                    b.Property<int>("ProjectPartakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcceptedTime")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.Property<bool>("Submitted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SubmittedTime")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ProjectPartakeId");

                    b.HasIndex("ProjectCode");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectPartakes");
                });

            modelBuilder.Entity("NTR.Models.Subcode", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.HasKey("Name");

                    b.HasIndex("ProjectCode");

                    b.ToTable("Subcodes");
                });

            modelBuilder.Entity("NTR.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NTR.Models.Activity", b =>
                {
                    b.HasOne("NTR.Models.Project", "Project")
                        .WithMany("Activities")
                        .HasForeignKey("ProjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NTR.Models.Subcode", "Subcode")
                        .WithMany()
                        .HasForeignKey("SubcodeName");

                    b.HasOne("NTR.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Subcode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NTR.Models.Project", b =>
                {
                    b.HasOne("NTR.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NTR.Models.ProjectPartake", b =>
                {
                    b.HasOne("NTR.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NTR.Models.User", "User")
                        .WithMany("ProjectPartakes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NTR.Models.Subcode", b =>
                {
                    b.HasOne("NTR.Models.Project", "Projects")
                        .WithMany("Subcodes")
                        .HasForeignKey("ProjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("NTR.Models.Project", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Subcodes");
                });

            modelBuilder.Entity("NTR.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ProjectPartakes");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
