version: '3'

services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'NTR'
      MYSQL_USER: 'NTR'
      MYSQL_PASSWORD: 'NTR'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "54321:3306"